styleloftproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

    path('payment/', views.payment, name='payment'),
    path('checkout/', views.checkout, name='checkout'),



]

styleloftproject/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]

styleloftproject/shopowner/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views



app_name = 'shopowner'

urlpatterns = [

    path('owner_registration/', views.owner_registration, name='owner_registration'),
    path('owner_login/', views.owner_login, name='owner_login'),

    path('logout/', views.logout_shopowner, name='logout_shopowner'),

    path('reset_owner_password/', auth_views.PasswordResetView.as_view(), name='reset_owner_password'),
    path('reset_owner_password/done/', auth_views.PasswordResetDoneView.as_view(), name='reset_owner_password_done'),
    path('reset_owner_password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name='reset_owner_password_confirm'),
    path('reset_owner_password/complete/', auth_views.PasswordResetCompleteView.as_view(),name='reset_owner_password_complete'),


    path('referal/', views.Referals, name='referal'),

    path('Femaleshopowner1/', views.Femaleshopowner1, name='Femaleshopowner1'),
    path('Femaleshopowner2/', views.Femaleshopowner2, name='Femaleshopowner2'),
    path('Femaleshopowner3/', views.Femaleshopowner3, name='Femaleshopowner3'),
    path('Femaleshopowner4/', views.Femaleshopowner4, name='Femaleshopowner4'),

    path('Maleshopowner1/', views.Maleshopowner1, name='Maleshopowner1'),
    path('Maleshopowner2/', views.Maleshopowner2, name='Maleshopowner2'),
    path('Maleshopowner3/', views.Maleshopowner3, name='Maleshopowner3'),
    path('Maleshopowner4/', views.Maleshopowner4, name='Maleshopowner4'),

]

styleloftproject/styleloftproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("styleapp.urls")),
    path('shop/', include("shop.urls")),
    path('search/', include("search_app.urls")),
    path('cart/', include("cart.urls")),
    path('bookingapp/', include("bookingapp.urls")),
    path('shopowner/', include("shopowner.urls")),
    path('password_reset/', include('django.contrib.auth.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

styleloftproject/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)


    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

class OrderStatus(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=250, blank=True)


    class Meta:
        verbose_name = 'orderstatus'
        verbose_name_plural = 'orderstatus'

    def __str__(self):
        return '{}'.format(self.name)


class Delivary(models.Model):

    address_line_1 = models.CharField(max_length=250, blank=True)
    address_line_2 = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=250, blank=True)
    state = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=250, blank=True)
    mobile_number = models.CharField(max_length=250, blank=True)
    email = models.CharField(max_length=250, blank=True)
    name = models.CharField(max_length=250, blank=True)

    class Meta:
        verbose_name = 'delivary'
        verbose_name_plural = 'delivary'

    def __str__(self):
        return '{}'.format(self.name)

styleloftproject/shopowner/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class ShopOwner(models.Model):
    username = models.CharField(max_length=250)
    shop_name = models.CharField(max_length=250)
    password = models.SlugField(max_length=250,blank=True)
    email = models.EmailField(max_length=250)
    path = models.CharField(max_length=250)
    referal = models.CharField(max_length=250,blank=True)
    user = models.CharField(max_length=250,blank=True)



    class Meta:
        verbose_name = 'shopowner'
        verbose_name_plural = 'shopowners'

    def __str__(self):
        return '{}'.format(self.shop_name)



class Referal(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    No_of_offers = models.CharField(max_length=250, blank=True)


    class Meta:
        verbose_name = 'referal'
        verbose_name_plural = 'referals'

    def __str__(self):
        return '{}'.format(self.name)



class PasswordResetRequest(models.Model):
    shop_owner = models.ForeignKey(ShopOwner, on_delete=models.CASCADE)
    token = models.CharField(max_length=32)
    created_at = models.DateTimeField(auto_now_add=True)

styleloftproject/cart/views.py
import razorpay
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt

from shop.models import Product
from .models import Cart, CartItem, OrderStatus, Delivary


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request, total=0, counter=0, cart_items=None, status=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    # Filter OrderStatus objects based on the user associated with the request
    user_status = OrderStatus.objects.filter(name=request.user)
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter, status=user_status))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')


@csrf_exempt
def payment(request):
    # Razorpay credentials
    razorpay_key_id = "rzp_test_zddK1OzkWyN71o"
    razorpay_key_secret = "Q2RDsJ83DWNht8jtFtLK2EuB"

    client = razorpay.Client(auth=(razorpay_key_id, razorpay_key_secret))

    if request.method == 'POST':
        # Process the payment response
        response = request.POST
        order_id = response['razorpay_order_id']
        payment_id = response['razorpay_payment_id']
        signature = response['razorpay_signature']

        try:
            client.utility.verify_payment_signature({
                'razorpay_order_id': order_id,
                'razorpay_payment_id': payment_id,
                'razorpay_signature': signature
            })
            # Payment successful, update the payment status in your system
            # return HttpResponse("Payment Successful")
            return redirect('/cart/checkout')
        except Exception as e:
            # Payment verification failed, handle the failure case
            return HttpResponse("Payment Verification Failed")
    else:
        # Get the total amount from the cart
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        total_amount = sum(cart_item.product.price * cart_item.quantity for cart_item in cart_items)

        # Generate unique order ID and other required parameters
        order_amount = int(total_amount * 100)  # Amount should be in paise (e.g., Rs 500 should be 50000)
        order_currency = "INR"
        order_receipt = "<generate_unique_order_receipt>"

        # Create an order in Razorpay
        order = client.order.create({
            'amount': order_amount,
            'currency': order_currency,
            'receipt': order_receipt,
            'payment_capture': '1'  # Auto-capture payment after successful redirect
        })

        # Create a context with necessary parameters
        context = {
            'order_id': order['id'],
            'order_amount': order_amount,
            'order_currency': order['currency'],
            'order_receipt': order['receipt'],
            'razorpay_key_id': razorpay_key_id
        }

        return render(request, "payment.html", context)

@login_required
def checkout(request):
    if request.method == "POST":
        address_line_1 = request.POST.get('address_line_1', '')
        address_line_2 = request.POST.get('address_line_2', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        postal_code = request.POST.get('postal_code', '')
        mobile_number = request.POST.get('mobile_number', '')
        name = request.POST.get('name', '')
        email = request.POST.get('name', '')

        delivary = Delivary(address_line_1=address_line_1, address_line_2=address_line_2, city=city, state=state, postal_code=postal_code,mobile_number=mobile_number,name=name,email=email)
        delivary.save()
        return redirect('/shop')
    return render(request, "checkout.html")

styleloftproject/templates/female_shop4_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

styleloftproject/templates/payment.html
{% extends 'base.html' %}}
{% load static %}
{% block metadescription %}
This is the cart page. Proceed to review your items and place the order
{% endblock %}
{% block title %}
cart-styleloft Company PVT LTD
{% endblock %}
{% block content %}

<center>
<h1 style="color:red;">payment</h1>

<!-- myapp/templates/payment.html -->

<!-- myapp/templates/payment.html -->

<!--<form action="https://api.razorpay.com/v1/payment/order_{{ order_id }}/capture/" method="POST">-->
<!--  {% csrf_token %}-->
<!--  <script src="https://checkout.razorpay.com/v1/checkout.js"-->
<!--          data-key="{{ razorpay_key_id }}"-->
<!--          data-amount="{{ order_amount }}"-->
<!--          data-currency="{{ order_currency }}"-->
<!--          data-order_id="{{ order_id }}"-->
<!--          data-buttontext="Pay with Razorpay"-->
<!--          data-name="My Store"-->
<!--          data-description="Order #{{ order_receipt }}"-->
<!--          data-image="https://your_logo_url.png"-->
<!--          data-prefill.name="{{user.username}}"-->
<!--          data-prefill.email="johndoe@example.com"-->
<!--          data-theme.color="#F37254"-->
<!--  ></script>-->
<!--</form>-->


<!-- myapp/templates/payment.html -->

<form action="{% url 'cart:payment' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="razorpay_order_id" value="{{ order_id }}">
  <input type="hidden" name="razorpay_payment_id" value="">
  <input type="hidden" name="razorpay_signature" value="">
  <script src="https://checkout.razorpay.com/v1/checkout.js"
          data-key="{{ razorpay_key_id }}"
          data-amount="{{ order_amount }}"
          data-currency="{{ order_currency }}"
          data-order_id="{{ order_id }}"
          data-buttontext="Pay with Razorpay"
          data-name="Styleloft Store"
          data-description="Order #{{ order_receipt }}"
          data-image="https://your_logo_url.png"
          data-prefill.name="{{user.username}}"
          data-prefill.email="{{user.email}}"
          data-theme.color="#F37254"
  ></script>
</form>


</center>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

styleloftproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{{ product.description|truncatewords:155 }}

{% endblock %}

{% block title %}
{% if category %}
{{ product.name }} -styleloft Store

{% endif %}
{% endblock %}
{% block content %}


<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">Home</a>|<a
                href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:28rem">

                    <img src="{{product.image.url}}" alt="{{product.name}}" class="img-fluid">

                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>

                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p><b>Rs {{product.price}}</b></p>
                    <br><br>
                    <p class="my_title"><b>Product Description</b></p>
                    <p class="text_justify my_prod_text">{{product.description|linebreaksbr}}</p>

                    {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                    <br> <br> <br>
                    <br> <br> <br>
                    <br><br><br>
                    <br><br><br>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

styleloftproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
we have variety of products
{{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
Search
{% endblock %}

{% block content %}

<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">

        {% for product in products %}

        <div class="my_bottom-margin col-3 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card  text-center" style="min-width:19rem; min-height:25rem;">


                <a href="{{product.get_url}}"><img class="card-img-top my_image " src="{{product.image.url}}"
                                                   alt="{{product.name}}"></a>


                <div class="card-body">

                    <h4>{{product.name}}</h4>
                    <p>Rs {{product.price}}</p>

                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text">No results found</p>
        </div>
        {% endfor %}
    </div>
</div>
<br><br><br>
<br><br><br>
<br><br><br>
<br><br><br>
{% endblock %}